---

# Installation 

- name: Add MongoDB repo file
  yum_repository:
    name: mongodb-org-3.4.repo
    description: MongoDB YUM repo
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc

- name: Install MongoDB packages and associated tools
  yum:
    name: mongodb-org
    state: present

- name: Start MongoDB daemon
  command: systemctl start mongod

- name: Install job performance module supremm
  yum: 
    name: "{{ supremm_url }}" 
    state: present

