---

# Installation 

- name: Add MongoDB repo file
  yum_repository:
    name: mongodb-org-3.4.repo
    description: MongoDB YUM repo
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.4/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-3.4.asc

